name: Publish to npm

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  workflow_run:
    workflows: ["Publish to npm"]
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ou a versão de Node.js que você está usando
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  publish:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ou a versão de Node.js que você está usando
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@your-scope'  # Se a sua biblioteca for escopada

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create a release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
